version: "3.9"

services:
  # --- NestJS App ---
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: webblog-backend-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: db # service 'db'
      DB_PORT: "5432"
      DB_USERNAME: postgres
      DB_PASSWORD: 1111
      DB_DATABASE: blog
      JWT_SECRET: devsecret
    depends_on:
      - db
    networks:
      - kong-net

  # --- Database ---
  db:
    image: postgres:16
    container_name: blog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: blog
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kong-net

  # --- Kong DB ---
  kong-database:
    image: postgres:16
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data

# --- Kong Migrations ---
  kong-migrations:
    image: kong:3.6
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    networks:
      - kong-net

# --- Kong Gateway ---
  kong-gateway:
    image: kong:3.6
    depends_on:
      - kong-database
      - kong-migrations
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: "${KONG_ADMIN_GUI_LISTEN:-0.0.0.0:8002}"
    ports:
      - "8000:8000" # public API gateway
      - "8001:8001" # admin API
      - "8002:8002" # admin GUI
    networks:
      - kong-net

# กำหนด Network และ Volume ใหม่
networks:
  kong-net:
    driver: bridge

volumes:
  pgdata: {}
  kong_data: {}