version: "3.9"

services:
  # NestJS App
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: webblog-backend-dev
    ports:
      - "3000:3000"
    # expose:
    #   - "3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: db # service 'db'
      DB_PORT: "5432"
      DB_USERNAME: postgres
      DB_PASSWORD: 1111
      DB_DATABASE: blog
      JWT_SECRET: devsecret
    depends_on:
      - db
    # Network กลาง
    networks:
      - kong-net

  # App Database
  db:
    image: postgres:16
    container_name: blog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Network กลาง
    networks:
      - kong-net

  # Kong DB
  kong-db:
    image: postgres:13
    container_name: kong-database
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: your_kong_db_password
    networks:
      - kong-net
    volumes:
      - kong_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Kong Migrations
  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db # service 'kong-db'
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: your_kong_db_password
    command: "kong migrations bootstrap"
    restart: on-failure
    networks:
      - kong-net
    depends_on:
      kong-db:
        condition: service_healthy

  # Kong Gateway
  kong-gateway:
    image: kong:latest
    container_name: kong-gateway
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: your_kong_db_password
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    ports:
      # พอร์ตที่รับ Traffic จากภายนอก
      - "80:8000"   # Traffic หลัก (HTTP)
      - "443:8443"  # Traffic หลัก (HTTPS)
      - "8001:8001" # Admin API สำหรับตั้งค่า
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      kong-migrations:
        condition: service_completed_successfully

# กำหนด Network และ Volume ใหม่
networks:
  kong-net:
    driver: bridge

volumes:
  pgdata: {} 
  kong_db_data: {}